### PR TITLE
feat: add GREASEEncryptedClientHelloExtension

### PR DESCRIPTION
**Pull request by gaukas**
- [x] Finalize `EncryptedClientHelloExtension` interface
- Add `GREASEEncryptedClientHelloExtension` extension
    - ~Correctly calculate the length of `EncodedClientHelloInner`~
    - [x] Allow specifying the length of `payload` 
    - [x] Randomize cipher suite, config id, enc, and payload
- [x] Handle EncryptedExtension `encrypted_client_hello` 

----

## Reference
- **crypto/tls: implement draft-ietf-tls-esni-13** under https://github.com/cloudflare/go/commits/cf/src/crypto/tls

### CODE REVIEW

**Comment by gaukas** [comment]
@VeNoMouS, feel free to either rebase your work on this branch/PR or just take it as a reference (if you had a pretty much incompatible implementation). 

These changes are heavily based on `cloudflare/go` so later if we are porting the full support of ECH it may save us some effort.

**Comment by VeNoMouS** [comment]
@gaukas you on discord, can discuss other stuff your missing

**Comment by gaukas** [comment]
Sure, we can setup a meeting. I am pretty booked today until night (~6PM Mountain or later) and will have more time tomorrow. Lemme know your availability?

**Comment by VeNoMouS** [comment]
My timezone is NZDT, I'm mostly booked in the evening for rest of the week due to time of year 

grab my discord off my gh profile and hmu and we can have a discussion

**Pull request merged**
