### PR TITLE
fix: Reuse existing PreSharedKeyExtension bug (#248)

### PR DESCRIPTION
**Pull request by VeNoMouS**

### CODE REVIEW

**Review by gaukas — APPROVED** [review]
Looks good to me! 

Have you tested and are these everything needed to get the bug fixed? Please double check to make sure the [examples](https://github.com/refraction-networking/utls/tree/master/examples/tls-resumption) for session resumption works.

**Comment by VeNoMouS** [comment]
> Looks good to me!
> 
> Have you tested and are these everything needed to get the bug fixed? Please double check to make sure the [examples](https://github.com/refraction-networking/utls/tree/master/examples/tls-resumption) for session resumption works.

Was working in my dev, but let me double check from a clean pull, so all my dev debugging etc from the other week is gone

**Comment by VeNoMouS** [comment]
All appears to be working as should, raw bytes && tls-resumption example

**Comment by gaukas** [comment]
Thanks!

**Pull request merged**
